Chore: Refactor Code & Change PHP Version
- Change docker PHP version from 8.1 to 8.2.
- Modify pre-commit hooks to use Docker PHP version instead of system.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,11 +2,11 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 echo "\nRunning static code analysis..."
-./vendor/bin/phpstan analyse && EXIT_CODE=$? && if [ $EXIT_CODE -gt 0 ]; then echo "Larastan analysis failed with error(s)"; exit 1; fi;
+docker exec docker-pet-php-container ./vendor/bin/phpstan analyse && EXIT_CODE=$? && if [ $EXIT_CODE -gt 0 ]; then echo "Larastan analysis failed with error(s)"; exit 1; fi;
 
 # Run PHP Insights and capture output
 echo "\nRunning code quality analysis..."
-INSIGHTS_OUTPUT=$(php artisan insights --format=json)
+INSIGHTS_OUTPUT=$(docker exec docker-pet-php-container php artisan insights --format=json)
 
 # Extract quality gate score from output
 CODE_SCORE=$(php -r '$output = json_decode($argv[1], true); echo (int) $output["summary"]["code"];' "$INSIGHTS_OUTPUT")
